### ISSUE TITLE
Calchart ignoring reference points/transitions

### ISSUE THREAD

**Issue by shaytudhope-stack** [calband/calchart#694]
I ran into this issue trying to code a counter march where calchart would just ignore the reference points I set up and just have the points continue marching into oblivion. Then I noticed it was doing it to all of the previous transitions as well. It was just ignoring where the dot was supposed to pivot and just continuing straight until it went off the screen. I am on the latest version on windows. 

https://drive.google.com/file/d/1SkN8BWfWtdOPyy9HSYR-xJ9_sXDU1dQB/view?usp=sharing

**Comment by rmpowell77** [comment]
What do we see when you have draw paths enabled?

**Comment by rmpowell77** [comment]
I think I fixed this with #828

**Comment by aniela-patalita** [comment]
> I think I fixed this with [#828](https://github.com/calband/calchart/pull/828)

This is still happening on 3.8.9. These videos are from 3.8.1, 3.8.6, and 3.8.9, respectively. I use 8.6.8 to avoid the issue.

https://drive.google.com/file/d/101AWS1ddIyzhA9aHkknXcDpJmuRZ4xn6/view?usp=sharing 
https://drive.google.com/file/d/11UGghNpzy5Z9Re8ecVvhVCYZAN0D5JbV/view?usp=sharing
https://drive.google.com/file/d/1_OA1TDSSqr53vPzPBWgTItVcPyG0UB7P/view?usp=sharing

**Comment by rmpowell77** [comment]
This is fixed with #853
